apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-demo
  namespace: interns-dev
 
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: otp-site
        image: 11varunsharma/project3:version1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: otp-entrypoint
  namespace: interns-dev
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30007